#!/usr/bin/env python
# coding: utf-8

# In[1]:


from fuzzywuzzy import process,fuzz


# In[2]:


extractDict = dict()

extractTruong = {
'ĐH BK':'BK',
'ĐH Bách Khoa':'BK',
'ĐH Bach Khoa':'BK',
'Đại học BK':'BK',
'Đại học Bách khoa':'BK',
'Bách Khoa':'BK',
'BK':'BK',
'ĐH Công Nghệ Thông Tin Gia Định':'GIADINH',
'ĐH CNTT Gia Định':'GIADINH',
'ĐH Gia Định':'GIADINH',
'Đại học Công Nghệ Thông Tin Gia Định':'GIADINH',
'Đại học CNTT Gia Định':'GIADINH',
'Đại học Gia Định':'GIADINH',
'Gia Định':'GIADINH',
'ĐH Văn Lang':'VLU',
'Đại học Văn Lang':'VLU',
'Văn Lang':'VLU',
'VLU':'VLU',
'Đại học FPT':'FPT',
'ĐH FPT':'FPT',
'ĐHFPT':'FPT',
'FPT':'FPT',
'ĐH Hoa Sen':'HOASEN',
'Đại học Hoa Sen':'HOASEN',
'Hoa Sen':'HOASEN',
'Đại học Hùng Vương':'HVU',
'ĐH Hùng Vương':'HVU',
'Hùng Vương':'HVU',
'HVU':'HVU',
'ĐH Kinh tế - Tài Chính':'UEF',
'ĐH KTTC':'UEF',
'ĐH KT- TC':'UEF',
'ĐHKTTC':'UEF',
'ĐHKT-TC':'UEF',
'Đại học Kinh tế TC':'UEF',
'Đại học KT Tài Chính':'UEF',
'ĐH Kinh tế TC':'UEF',
'ĐH KT Tài Chính':'UEF',
'Đại học KTTC':'UEF',
'Đại học KT_TC':'UEF',
'UEF':'UEF',
'ĐH Tin học - Ngoại ngữ':'HUFLIT',
'ĐH THNN':'HUFLIT',
'ĐH Tin học - NN':'HUFLIT',
'ĐH TH- Ngoại ngữ':'HUFLIT',
'Đại học Tin học - Ngoại ngữ':'HUFLIT',
'Đại học THNN':'HUFLIT',
'Đại học Tin học - NN':'HUFLIT',
'Đại học TH- Ngoại ngữ':'HUFLIT',
'HUFLIT':'HUFLIT',
'Đại học Thủ Dầu Một':'TDMU',
'ĐH Thủ Dầu Một':'TDMU',
'ĐHThủ Dầu Một':'TDMU',
'ĐHTDM':'TDMU',
'Đại học TDM':'TDMU',
'TDMU':'TDMU',
'thủ dầu một': 'TDMU',
'ĐH QT Hồng Bàng':'HIU',
'ĐH Quốc tế Hồng Bàng':'HIU',
'ĐHQTHB':'HIU',
'ĐH QTHB':'HIU',
'Đại học QT Hồng Bàng':'HIU',
'Đại học Quốc tế Hồng Bàng':'HIU',
'Đại học QTHB':'HIU',
'HIU':'HIU',
'Đại học Lạc Hồng':'LHU',
'ĐH Lạc Hồng':'LHU',
'ĐHLạc Hồng':'LHU',
'ĐHLHồng':'LHU',
'LHU':'LHU',
'Đại học Quốc tế Sài Gòn':'SIU',
'ĐH QTSG':'SIU',
'ĐH Quốc tế Sài gòn':'SIU',
'SIU':'SIU',
'Đại học Văn Hiến':'VHU',
'ĐH Văn Hiến':'VHU',
'Văn Hiến':'VHU',
'VHU':'VHU',
'Đại học An Giang':'AGU',
'ĐH An Giang':'AGU',
'ĐHAG':'AGU',
'AGU':'AGU',
'Đại học Y Cần Thơ':'YCT',
'ĐH Y Cần Thơ':'YCT',
'Y Cần Thơ':'YCT',
'YCT':'YCT',
'Đại học An Ninh Nhân Dân':'T47',
'Đại học ANND':'T47',
'ĐH An Ninh Nhân Dân':'T47',
'ĐH ANND':'T47',
'T47':'T47',
'Đại học  Công Nghiệp Thực Phẩm':'HUFI',
'Đại học CNTP':'HUFI',
'Công nghiệp thực phẩm':'HUFI',
'ĐH  công nghiệp thực phẩm':'HUFI',
'ĐH CNTP':'HUFI',
'ĐHCNTP':'HUFI',
'HUFI':'HUFI',
'Đại học Công Nghiệp':'IUH',
'ĐH Công Nghiệp':'IUH',
'Công Nghiêp':'IUH',
'ĐH CN':'IUH',
'ĐHCN':'IUH',
'IUH':'IUH',
'Đại học Công Nghệ Thông Tin':'UIT',
'ĐH công nghệ thông tin ':'UIT',
'đại học CNTT':'UIT',
'ĐH CNTT':'UIT',
'ĐHCNTT':'UIT',
'UIT':'UIT',
'Đại học Cần Thơ':'CTU',
'ĐH Cần Thơ':'CTU',
'ĐHCT':'CTU',
'CTU':'CTU',
'Đại học Giao Thông Vận Tải':'UTC',
'ĐH Giao Thông Vận Tải ':'UTC',
'ĐH GTVT ':'UTC',
'Đại học GTVT ':'UTC',
'ĐH Giao Thông VT ':'UTC',
'ĐH GT Vận Tải ':'UTC',
'ĐHGTVT ':'UTC',
'UTC':'UTC',
'đại học khoa học tự nhiên':'HCMUS',
'Đại học KHTN':'HCMUS',
'ĐH khoa học tự nhiên':'HCMUS',
'ĐH KHTN':'HCMUS',
'ĐHKHTN':'HCMUS',
'Khoa Học Tự Nhiên':'HCMUS',
'KHTN':'HCMUS',
'HCMUS':'HCMUS',
'đại học khoa học xã hội và nhân văn':'USH',
'Đại học KHXHNV':'USH',
'ĐH khoa học xã hội và nhân văn':'USH',
'ĐH KHXHNV':'USH',
'ĐHKHXHNV':'USH',
'KHXHNV':'USH',
'Khoa Học Xã Hội Nhân Văn':'USH',
'Xã Hội Nhân Văn':'USH',
'USH':'USH',
'đại học kinh tế - luật':'UEL',
'ĐH Kinh Tế - Luật':'UEL',
'Kinh Tế - Luật':'UEL',
'KTL':'UEL',
'UEL':'UEL',
'đại học kinh tế ':'UEH',
'ĐH Kinh Tế':'UEH',
'ĐHKT':'UEH',
'ĐH KT':'UEH',
'UEH':'UEH',
'Đại học Kiến Trúc':'UAH',
'ĐH Kiến Trúc':'UAH',
'Kiến Trúc':'UAH',
'ĐHKiến Trúc':'UAH',
'ĐH K.Trúc':'UAH',
'UAH':'UAH',
'Đại Học Lao Động - Xã hội cơ sở 2':'ULSA2',
'ĐH Lao Động - Xã hội cơ sở 2':'ULSA3',
'Đại Học Lao Động - Xã hội 2':'ULSA4',
'ĐH Lao Động - Xã hội 2':'ULSA5',
'ĐHLĐXH2':'ULSA6',
'ĐH LĐXH2':'ULSA7',
'LĐXH2':'ULSA8',
'ULSA2':'ULSA9',
'Đại học Luật':'ULAW',
'ĐH Luật':'ULAW',
'ĐHL':'ULAW',
'ĐHLuật':'ULAW',
'Luật':'ULAW',
'ULAW':'ULAW',
'Đại học mở':'OU',
'ĐH Mở':'OU',
'ĐHMở':'OU',
'Mở':'OU',
'OU':'OU',
'Đại học mỹ thuật':'MT',
'ĐH Mỹ Thuật':'MT',
'ĐHMT':'MT',
'ĐH MT':'MT',
'MT':'MT',
'Đại học ngọai thương cơ sở phía Nam':'FTU',
'ĐH Ngoại Thương':'FTU',
'Ngoại Thương':'FTU',
'ĐHNgT':'FTU',
'FTU':'FTU',
'Đại học ngân hàng':'BUH',
'ĐH Ngân Hàng':'BUH',
'Ngân Hàng':'BUH',
'BUH':'BUH',
'ĐH Ng Hàng':'BUH',
'Đại học Nông Lâm':'NLU',
'ĐH Nông Lâm':'NLU',
'ĐHNLâm':'NLU',
'Nông Lâm':'NLU',
'NLU':'NLU',
'Đại học Quốc Tế':'IU',
'ĐHQT':'IU',
'ĐH QT':'IU',
'ĐH Quốc Tế':'IU',
'IU':'IU',
'Đại học Sài Gòn':'SGU',
'ĐH Sài Gòn':'SGU',
'Sài Gòn':'SGU',
'ĐHSG':'SGU',
'ĐH SG':'SGU',
'Đại học SG':'SGU',
'SGU':'SGU',
'Đại học Sân Khấu diện ảnh':'SKDAHCM',
'ĐH Sân Khấu Điện Ảnh':'SKDAHCM',
'Đại học SKĐA':'SKDAHCM',
'ĐHSKĐA':'SKDAHCM',
'Sân Khấu Điện Ảnh':'SKDAHCM',
'SKĐA':'SKDAHCM',
'SKDAHCM':'SKDAHCM',
'Đại học sư phạm kĩ thuật':'UTE',
'ĐH Sư Phạm Kĩ Thuật':'UTE',
'Đại học sư phạm kỹ thuật':'UTE',
'ĐH Sư Phạm Kỹ Thuật':'UTE',
'ĐH SPKT':'UTE',
'ĐHSPKT':'UTE',
'SPKT':'UTE',
'Sư Phạm Kĩ Thuật':'UTE',
'Sư Phạm Kỹ Thuật':'UTE',
'UTE':'UTE',
'Đại học Sư phạm':'HCMUE',
'ĐH Sư Phạm':'HCMUE',
'Đại học Sư phạm Thành Phố Hồ Chí Minh':'HCMUE',
'ĐH Sư phạm Thành Phố Hồ Chí Minh':'HCMUE',
'Đại học Sư phạm Hồ Chí Minh':'HCMUE',
'ĐH Sư phạm Hồ Chí Minh':'HCMUE',
'ĐHSP':'HCMUE',
'ĐH SP':'HCMUE',
'ĐHSPHCM':'HCMUE',
'ĐHSPTPHCM':'HCMUE',
'ĐH SPHCM':'HCMUE',
'ĐH SPTPHCM':'HCMUE',
'HCMUE':'HCMUE',
'Đại học Trần Đại Nghĩa':'TDNU',
'ĐH Trần Đại Nghĩa':'TDNU',
'ĐH TĐN':'TDNU',
'ĐHTĐN':'TDNU',
'TDNU':'TDNU',
'Đại học Tài chính - Marketing':'UFM',
'ĐH Tài chính - Marketing':'UFM',
'Đại học Tài chính Marketing':'UFM',
'ĐH Tài chính Marketing':'UFM',
'ĐHTCMT':'UFM',
'Tài chính Marketing':'UFM',
'UFM':'UFM',
'Đại học Tài nguyên - Môi trường':'NRE',
'ĐH Tài Nguyên - Môi Trường':'NRE',
'Đại học Tài nguyên Môi trường':'NRE',
'ĐH Tài Nguyên Môi Trường':'NRE',
'Đại học TNMT':'NRE',
'ĐH TNMT':'NRE',
'ĐHTNMT':'NRE',
'NRE':'NRE',
'Đại học Tôn Đức Thắng':'TDTU',
'ĐH Tôn Đức Thắng':'TDTU',
'Đại học TĐT':'TDTU',
'ĐH TĐT':'TDTU',
'Đại học TDT':'TDTU',
'ĐH TDT':'TDTU',
'ĐHTĐT':'TDTU',
'ĐHTDT':'TDTU',
'TDTU':'TDTU',
'Đại học Lạc Hồng':'LHU',
'ĐH Lạc Hồng':'LHU',
'ĐH LHồng':'LHU',
'Lạc Hồng':'LHU',
'LHU':'LHU',
'Đại học Bình Dương':'BDU',
'ĐH Bình Dương':'BDU',
'ĐHBình Dương':'BDU',
'ĐHBDương':'BDU',
'BDU':'BDU',
'Đại học Y Dược ':'UMP',
'ĐH Y Dược':'UMP',
'Y Dược':'UMP',
'UMP':'UMP',
'Đại học Y khoa Phạm Ngọc Thạch':'PNT',
'ĐH Phạm Ngọc Thạch':'PNT',
'ĐH Y khoa Phạm Ngọc Thạch':'PNT',
'Y khoa Phạm Ngọc Thạch':'PNT',
'ĐH Y khoa PNT':'PNT',
'Đại học Y khoa PNT':'PNT',
'Y khoa PNT':'PNT',
'PNT':'PNT',
'Khoa Y- Đại học Quốc gia':'QSY',
'Khoa Y- ĐHQG':'QSY',
'Y- Đại học Quốc gia':'QSY',
'Y- ĐHQG':'QSY',
'Khoa Y Đại học Quốc gia':'QSY',
'Khoa Y ĐHQG':'QSY',
'Y Đại học Quốc gia':'QSY',
'Y ĐHQG':'QSY',
'QSY':'QSY',
'Đại học Công Nghệ':'HUTECH',
'ĐH Công Nghệ':'HUTECH',
'ĐHCông Nghệ':'HUTECH',
'ĐH CNghệ':'HUTECH',
'ĐHCNghệ':'HUTECH',
'HUTECH':'HUTECH',
'Đại học Công Nghệ Sài Gòn':'STU',
'ĐH Công Nghệ Sài Gòn':'STU',
'Đại học CNSG':'STU',
'ĐHCNSG':'STU',
'ĐH CNSG':'STU',
'STU':'STU',
'Đại học Công Nghệ SG':'STU',
'ĐH Công Nghệ SG':'STU',
'Trường Sĩ Quan Lục Quân 2':'NHU',
'Sĩ Quan Lục Quân 2':'NHU',
'Trường Sĩ Quan LQ2':'NHU',
'Trường SQLục Quân 2':'NHU',
'Trường SQLQ2':'NHU',
'SQLQ2':'NHU',
'SQLQ 2':'NHU',
'Đại học Nguyễn Huệ':'NHU',
'ĐH Nguyễn Huệ':'NHU',
'Đại học NHuệ':'NHU',
'ĐH NHuệ':'NHU'
}


# In[3]:


extractNganh = {
    'Hữu cơ-hóa dược':' Công nghệ hữu cơ - Hóa dược',
'Hữu cơ,hóa dược':' Công nghệ hữu cơ - Hóa dược',
'Hữu cơ, hóa dược':' Công nghệ hữu cơ - Hóa dược',
'Hữu cơ - hóa dược':' Công nghệ hữu cơ - Hóa dược',
'điện, điện tử':' Công nghệ kỹ thuật điện, điện tử',
'điện - điện tử':' Công nghệ kỹ thuật điện, điện tử',
'vô cơ, vật liệu':' Công nghệ Vô cơ - Vật liệu',
'vô cơ - vật liệu':' Công nghệ Vô cơ - Vật liệu',
'Đầu tư tài chính':' Đầu tư tài chính',
'đầu tư TC ':' Đầu tư tài chính',
'ĐT tài chính':' Đầu tư tài chính',
'Thông tin kinh doanh':' Hệ thống thông tin kinh doanh',
'Thông tin KD':' Hệ thống thông tin kinh doanh',
'TT Kinh doanh':' Hệ thống thông tin kinh doanh',
'hướng dẫn viên':' Hướng dẫn viên du lịch',
'HDV':' Hướng dẫn viên du lịch',
'QT dịch vụ du lịch và lữ hành':' Quản trị Dịch vụ Du lịch & Lữ hành',
'QT dịch vụ du lịch & lữ hành':' Quản trị Dịch vụ Du lịch & Lữ hành',
'QTDV du lịch và lữ hành':' Quản trị Dịch vụ Du lịch & Lữ hành',
'QTDV du lịch & lữ hành':' Quản trị Dịch vụ Du lịch & Lữ hành',
'du lịch và lữ hành':' Quản trị Dịch vụ Du lịch & Lữ hành',
'du lịch & lữ hành':' Quản trị Dịch vụ Du lịch & Lữ hành',
' Quản trị Dịch vụ Du lịch & Lữ hành':' Quản trị Dịch vụ Du lịch & Lữ hành',
'QTKS':' Quản trị khách sạn',
'Quản tri KS':' Quản trị khách sạn',
'QT khách sạn':' Quản trị khách sạn',
'Quản trị khách sạn':' Quản trị khách sạn',
'TCDN':' Tài chính doanh nghiệp',
'Tài chính DN':' Tài chính doanh nghiệp',
'TC Doanh nghiệp':' Tài chính doanh nghiệp',
'Tài chính doanh nghiệp':' Tài chính doanh nghiệp',
'TCNH':' Tài chính ngân hàng',
'Tài chính ngân hàng':' Tài chính ngân hàng',
'TC ngân hàng':' Tài chính ngân hàng',
'Tài chính NH':' Tài chính ngân hàng',
'xã hội học':' Xã hội học',
'XH học':' Xã hội học',
'Kỹ thuật xét nghiệm y học':' Kỹ thuật xét nghiệm y học',
'KT xét nghiệm y học':' Kỹ thuật xét nghiệm y học',
'KTXN y học':' Kỹ thuật xét nghiệm y học',
'KTXT':' Kỹ thuật xét nghiệm y học',
'Kỹ thuật xét nghiệm':' Kỹ thuật xét nghiệm y học',
'An toàn thông tin':'An toàn thông tin',
'An toàn TT':'An toàn thông tin',
'AT thông tin':'An toàn thông tin',
'ATTT':'An toàn thông tin',
'Công Nghệ Chế Biến Lâm Sản':'Công Nghệ Chế Biến Lâm Sản',
'CNCB lâm sản':'Công Nghệ Chế Biến Lâm Sản',
'CN chế biến lâm sản':'Công Nghệ Chế Biến Lâm Sản',
'công nghệ CB lâm sản':'Công Nghệ Chế Biến Lâm Sản',
'chế biến lâm sản':'Công Nghệ Chế Biến Lâm Sản',
'Công Nghệ Chế Biến thủy Sản':'Công nghệ chế biến thủy sản',
'CNCB thủy sản':'Công nghệ chế biến thủy sản',
'CN chế biến thủy sản':'Công nghệ chế biến thủy sản',
'công nghệ CB thủy sản':'Công nghệ chế biến thủy sản',
'chế biến thủy sản':'Công nghệ chế biến thủy sản',
'Công nghệ chế tạo máy':'Công nghệ chế tạo máy',
'CN chế tạo máy':'Công nghệ chế tạo máy',
'chế tạo máy':'Công nghệ chế tạo máy',
'Công nghệ dệt, may':'Công nghệ dệt, may',
'CN dệt may':'Công nghệ dệt, may',
'dệt may':'Công nghệ dệt, may',
'dệt, may':'Công nghệ dệt, may',
'Công Nghệ kĩ thuật điện tử-viễn thông':'Công Nghệ kĩ thuật điện tử-viễn thông',
'CN kỹ thuật điện tử - viễn thông':'Công Nghệ kĩ thuật điện tử-viễn thông',
'kỹ thuật điện tử - viễn thông':'Công Nghệ kĩ thuật điện tử-viễn thông',
' điện tử viễn thông':'Công Nghệ kĩ thuật điện tử-viễn thông',
' điện tử - viễn thông':'Công Nghệ kĩ thuật điện tử-viễn thông',
'KT điện tử viễn thông':'Công Nghệ kĩ thuật điện tử-viễn thông',
'KT điện tử - viễn thông':'Công Nghệ kĩ thuật điện tử-viễn thông',
'điện tử, viễn thông':'Công Nghệ kĩ thuật điện tử-viễn thông',
'Công Nghệ kĩ thuật điện - điện tử':'Công Nghệ kĩ thuật điện, điện tử',
'CNKT điện - điện tử':'Công Nghệ kĩ thuật điện, điện tử',
'KT điện - điện tử':'Công Nghệ kĩ thuật điện, điện tử',
'kỹ thuật điện - điện tử':'Công Nghệ kĩ thuật điện, điện tử',
'điện - điện tử':'Công Nghệ kĩ thuật điện, điện tử',
'điện, điện tử':'Công Nghệ kĩ thuật điện, điện tử',
'Công nghệ kĩ thuật máy tính':'Công nghệ kĩ thuật máy tính',
'CN kỹ thuật máy tính':'Công nghệ kĩ thuật máy tính',
'CNKT máy tính':'Công nghệ kĩ thuật máy tính',
'Công nghệ kĩ thuật môi trường':'Công nghệ kĩ thuật môi trường',
'CN kỹ thuật môi trường':'Công nghệ kĩ thuật môi trường',
'CNKT môi trường':'Công nghệ kĩ thuật môi trường',
'kỹ thuật môi trường':'Công nghệ kĩ thuật môi trường',
'KT môi trường':'Công nghệ kĩ thuật môi trường',
'môi trường':'Công nghệ kĩ thuật môi trường',
'Công nghệ kĩ thuật ô tô':'Công nghệ kĩ thuật ô tô',
'CN kỹ thuật ô tô':'Công nghệ kĩ thuật ô tô',
'CNKT ô tô':'Công nghệ kĩ thuật ô tô',
'kỹ thuật ô tô':'Công nghệ kĩ thuật ô tô',
'KT ô tô':'Công nghệ kĩ thuật ô tô',
'kỹ thuật ôtô':'Công nghệ kĩ thuật ô tô',
'KT ôtô':'Công nghệ kĩ thuật ô tô',
'Công nghệ kỹ thuật cơ điện tử':'Công nghệ kỹ thuật cơ điện tử',
'CN kỹ thuật cơ điện tử':'Công nghệ kỹ thuật cơ điện tử',
'CNKT cơ điện tử':'Công nghệ kỹ thuật cơ điện tử',
'kỹ thuật cơ điện tử':'Công nghệ kỹ thuật cơ điện tử',
'KT cơ điện tử':'Công nghệ kỹ thuật cơ điện tử',
'cơ điện tử':'Công nghệ kỹ thuật cơ điện tử',
'Công nghệ kỹ thuật công trình xây dựng':'Công nghệ kỹ thuật công trình xây dựng',
'CN kỹ thuật công trình xây dựng':'Công nghệ kỹ thuật công trình xây dựng',
'CNKT công trình xây dựng':'Công nghệ kỹ thuật công trình xây dựng',
'kỹ thuật công trình xây dựng':'Công nghệ kỹ thuật công trình xây dựng',
'KT công trình xây dựng':'Công nghệ kỹ thuật công trình xây dựng',
'công trình xây dựng':'Công nghệ kỹ thuật công trình xây dựng',
'Công nghệ kỹ thuật điều khiển và tự động hóa':'Công nghệ kỹ thuật điều khiển và tự động hóa',
'CN kỹ thuật điều khiển và tự động hóa':'Công nghệ kỹ thuật điều khiển và tự động hóa',
'CNKT điều khiển và tự động hóa':'Công nghệ kỹ thuật điều khiển và tự động hóa',
'kỹ thuật điều khiển và tự động hóa':'Công nghệ kỹ thuật điều khiển và tự động hóa',
'KT điều khiển và tự động hóa':'Công nghệ kỹ thuật điều khiển và tự động hóa',
'điều khiển và tự động hóa':'Công nghệ kỹ thuật điều khiển và tự động hóa',
'ĐK và tự động hóa':'Công nghệ kỹ thuật điều khiển và tự động hóa',
'điều khiển và TĐH':'Công nghệ kỹ thuật điều khiển và tự động hóa',
'Công nghệ phần mềm':'Công nghệ phần mềm',
'CN phần mềm':'Công nghệ phần mềm',
'CNPM':'Công nghệ phần mềm',
'Công nghệ thông tin':'Công nghệ thông tin',
'CNTT':'Công nghệ thông tin',
'Công nghệ TT':'Công nghệ thông tin',
'CN thông tin':'Công nghệ thông tin',
'Công nghệ thực phẩm ':'Công nghệ thực phẩm ',
'CNTP':'Công nghệ thực phẩm ',
'Công nghệ TP':'Công nghệ thực phẩm ',
'CN thực phẩm':'Công nghệ thực phẩm ',
'Quản trị lữ hành':'Quản trị lữ hành',
'QT lữ hành':'Quản trị lữ hành',
'Quản trị nhà hàng':'Quản trị nhà hàng',
'QT nhà hàng':'Quản trị nhà hàng',
'Quản trị nhà hàng & dịch vụ ăn uống':'Quản trị nhà hàng & dịch vụ ăn uống',
'QT nhà hàng & dịch vụ ăn uống':'Quản trị nhà hàng & dịch vụ ăn uống',
'QTNH& dịch vụ ăn uống':'Quản trị nhà hàng & dịch vụ ăn uống',
'QT nhà hàng, dịch vụ ăn uống':'Quản trị nhà hàng & dịch vụ ăn uống',
'QTNH, dịch vụ ăn uống':'Quản trị nhà hàng & dịch vụ ăn uống',
'QT nhà hàng và dịch vụ ăn uống':'Quản trị nhà hàng & dịch vụ ăn uống',
'QTNH và dịch vụ ăn uống':'Quản trị nhà hàng & dịch vụ ăn uống',
'Quản Trị Nhân Lực':'Quản Trị Nhân Lực',
'QT nhân lực':'Quản Trị Nhân Lực',
'răng,hàm,mặt':'Răng - Hàm - Mặt',
'răng, hàm, mặt':'Răng - Hàm - Mặt',
'Răng hàm mặt':'Răng - Hàm - Mặt',
'sư phạm âm nhạc':'Sư phạm Âm nhạc ',
'sp âm nhạc':'Sư phạm Âm nhạc ',
'sư phạm công nghệ':'Sư phạm công nghệ',
'Sp công nghệ':'Sư phạm công nghệ',
'sư phạm địa lí':'Sư phạm Địa lí',
'SP địa lí':'Sư phạm Địa lí',
'sư phạm địa lý':'Sư phạm Địa lí',
'SP địa lý':'Sư phạm Địa lí',
'sư phạm địa':'Sư phạm Địa lí',
'SP địa':'Sư phạm Địa lí',
'SPGDMN':'Sư phạm giáo dục Mầm non',
'sư phạm GD mầm non':'Sư phạm giáo dục Mầm non',
'SP giáo dục mầm non':'Sư phạm giáo dục Mầm non',
'SPGD mầm non':'Sư phạm giáo dục Mầm non',
'sư phạm GD thể chất':'Sư phạm giáo dục Thể chất',
'sp giáo dục thể chất':'Sư phạm giáo dục Thể chất',
'SPGD thể chất':'Sư phạm giáo dục Thể chất',
'SP giáo dục tiểu học':'Sư phạm giáo dục Tiểu học ',
'sư phạm GD tiểu học':'Sư phạm giáo dục Tiểu học ',
'SPGD tiểu học':'Sư phạm giáo dục Tiểu học ',
'sư phạm hóa học':'Sư phạm Hóa học',
'sp hóa học':'Sư phạm Hóa học',
'sư phạm hóa':'Sư phạm Hóa học',
'sp hóa':'Sư phạm Hóa học',
'sư phạm lịch sử':'Sư phạm Lịch sử',
'Sp lịch sử':'Sư phạm Lịch sử',
'sư phạm sử':'Sư phạm Lịch sử',
'Sp sử':'Sư phạm Lịch sử',
'SPMT':'Sư phạm Mỹ thuật',
'sư phạm mỹ thuật':'Sư phạm Mỹ thuật',
'sp mỹ thuật':'Sư phạm Mỹ thuật',
'sư phạm ngữ văn':'Sư phạm Ngữ Văn',
'SP ngữ văn':'Sư phạm Ngữ Văn',
'sư phạm văn':'Sư phạm Ngữ Văn',
'SP văn':'Sư phạm Ngữ Văn',
'SP sinh học':'Sư phạm Sinh học',
'SP sinh':'Sư phạm Sinh học',
'sư phạm sinh học':'Sư phạm Sinh học',
'sư phạm sinh':'Sư phạm Sinh học',
'sư phạm anh':'Sư phạm Tiếng Anh ',
'sp anh':'Sư phạm Tiếng Anh ',
'sư phạm tiếng nga':'Sư phạm Tiếng Nga',
'SP tiếng nga':'Sư phạm Tiếng Nga',
'sư phạm tiếng pháp':'Sư phạm tiếng Pháp',
'sp tiếng pháp':'Sư phạm tiếng Pháp',
'sư phạm tiếng trung quốc':'Sư pham Tiếng Trung Quốc',
'sp tiếng trung quốc':'Sư pham Tiếng Trung Quốc',
'sư phạm tiếng trung':'Sư pham Tiếng Trung Quốc',
'sp tiếng trung':'Sư pham Tiếng Trung Quốc',
'sư phạm tin học':'Sư phạm Tin học',
'SP tin học':'Sư phạm Tin học',
'sư phạm tin':'Sư phạm Tin học',
'SP tin':'Sư phạm Tin học',
'sư phạm toán học':'Sư Phạm Toán học ',
'SP toán học':'Sư Phạm Toán học ',
'sư phạm toán':'Sư Phạm Toán học ',
'Sp toán':'Sư Phạm Toán học ',
'sư phạm lý':'Sư phạm vật lí',
'sư phạm vật lý':'Sư phạm vật lí',
'SP Lý':'Sư phạm vật lí',
'SP vật lý':'Sư phạm vật lí',
'tài chính QT':'Tài chính quốc tế',
'TC quốc tế':'Tài chính quốc tế',
'TCQT':'Tài chính quốc tế',
'Tài chính quốc tế':'Tài chính quốc tế',
'TCNH':'Tài chính-Ngân hàng',
'TC ngân hàng':'Tài chính-Ngân hàng',
'tài chính NH':'Tài chính-Ngân hàng',
'Tài chính-Ngân hàng':'Tài chính-Ngân hàng',
'Thiết kế công nghiệp':'Thiết kế công nghiệp',
'TK công nghiệp':'Thiết kế công nghiệp',
'Thiết kế đồ họa':'Thiết kế đồ họa',
'TK đồ họa':'Thiết kế đồ họa',
'Thiết kế mỹ thuật sân khấu điện ảnh':'Thiết kế mỹ thuật sân khấu điện ảnh',
'TK mỹ thuật sân khấu điện ảnh':'Thiết kế mỹ thuật sân khấu điện ảnh',
'TKMT sân khấu điện ảnh':'Thiết kế mỹ thuật sân khấu điện ảnh',
'Thiết kế nội thất':'Thiết kế nội thất',
'TK nội thất':'Thiết kế nội thất',
'Thiết kế thời trang':'Thiết kế thời trang',
'TK thời trang':'Thiết kế thời trang',
'Thiết kế trang web':'Thiết kế trang web',
'TK trang web':'Thiết kế trang web',
'Thiết kế web':'Thiết kế trang web',
'TK web':'Thiết kế trang web',
}


# In[4]:


extractKhoiThi = {
'A': 'A00',
'A00':'A00',
'A01':'A01',
'B00':'B00',
'B':'B00',
'C00':'C00',
'C': 'C00',
'D': 'D01',
'D01':'D01',
'D02':'D02',
'D03':'D03',
'D04':'D04',
'D05':'D05',
'D06':'D06',
'A02':'A02',
'A03':'A03',
'A04':'A04',
'A05':'A05',
'A06':'A06',
'A07':'A07',
'A08':'A08',
'A09':'A09',
'A10':'A10',
'A11':'A11',
'A12':'A12',
'A14':'A14',
'A15':'A15',
'A16':'A16',
'A17':'A17',
'A18':'A18',
'B01':'B01',
'B02':'B02',
'B03':'B03',
'B04':'B04',
'B05':'B05',
'B08':'B08',
'C01':'C01',
'C02':'C02',
'C03':'C03',
'C04':'C04',
'C05':'C05',
'C06':'C06',
'C07':'C07',
'C08':'C08',
'C09':'C09',
'C10':'C10',
'C12':'C12',
'C13':'C13',
'C14':'C14',
'C15':'C15',
'C16':'C16',
'C17':'C17',
'C19':'C19',
'C20':'C20',
'D07':'D07',
'D08':'D08',
'D09':'D09',
'D10':'D10',
'D11':'D11',
'D12':'D12',
'D13':'D13',
'D14':'D14',
'D15':'D15',
'D16':'D16',
'D17':'D17',
'D18':'D18',
'D19':'D19',
'D20':'D20',
'D21':'D21',
'D22':'D22',
'D23':'D23',
'D24':'D24',
'D25':'D25',
'D26':'D26',
'D27':'D27',
'D28':'D28',
'D29':'D29',
'D30':'D30',
'D31':'D31',
'D32':'D32',
'D33':'D33',
'D34':'D34',
'D35':'D35',
'D41':'D41',
'D42':'D42',
'D43':'D43',
'D44':'D44',
'D45':'D45',
'D52':'D52',
'D54':'D54',
'D55':'D55',
'D61':'D61',
'D62':'D62',
'D63':'D63',
'D64':'D64',
'D65':'D65',
'D66':'D66',
'D68':'D68',
'D69':'D69',
'D70':'D70',
'D72':'D72',
'D73':'D73',
'D74':'D74',
'D75':'D75',
'D76':'D76',
'D77':'D77',
'D78':'D78',
'D79':'D79',
'D80':'D80',
'D81':'D81',
'D82':'D82',
'D83':'D83',
'D84':'D84',
'D85':'D85',
'D86':'D86',
'D87':'D87',
'D88':'D88',
'D90':'D90',
'D91':'D91',
'D92':'D92',
'D93':'D93',
'D94':'D94',
'D95':'D95',
'D96':'D96',
'D97':'D97',
'D98':'D98',
'D99':'D99',
'H00':'H00',
'H01':'H01',
'H02':'H02',
'H03':'H03',
'H04':'H04',
'H05':'H05',
'H06':'H06',
'H07':'H07',
'H08':'H08',
'K01':'K01',
'M00':'M00',
'M01':'M01',
'M02':'M02',
'M03':'M03',
'M04':'M04',
'M09':'M09',
'M10':'M10',
'M11':'M11',
'M13':'M13',
'M14':'M14',
'M15':'M15',
'M16':'M16',
'M17':'M17',
'M18':'M18',
'M19':'M19',
'M20':'M20',
'M21':'M21',
'M22':'M22',
'M23':'M23',
'M24':'M24',
'M25':'M25',
'N00':'N00',
'N01':'N01',
'N02':'N02',
'N03':'N03',
'N04':'N04',
'N05':'N05',
'N06':'N06',
'N07':'N07',
'N08':'N08',
'N09':'N09',
'R00':'R00',
'R01':'R01',
'R02':'R02',
'R03':'R03',
'R04':'R04',
'R05':'R05',
'S00':'S00',
'S01':'S01',
'T00':'T00',
'T01':'T01',
'T02':'T02',
'T03':'T03',
'T04':'T04',
'T05':'T05',
'V':'V00',
'V00':'V00',
'V01':'V01',
'V02':'V02',
'V03':'V03',
'V04':'V04',
'V05':'V05',
'V06':'V06',
'V07':'V07',
'V08':'V08',
'V09':'V09',
'V10':'V10',
'V11':'V11',
} 


# In[5]:


extractDict['Truong'] = extractTruong
extractDict['NganhHoc'] = extractNganh
# extractDict['KhoiThi'] = extractKhoiThi


# In[6]:


def is_float(value):
    try:
        float(value)
        return True
    except:
        return False


# In[12]:


def extract(text):
    THRESHOLD = 91
    listExtract = []
    for key in extractDict:
        keyDict = extractDict[key]
        for value in keyDict:
            if fuzz.partial_ratio(text.lower(), value.lower()) >= THRESHOLD: 
                extractEle = dict()
                extractEle["value"] = keyDict[value]
                extractEle["key"] = key
                listExtract.append(extractEle)
                print(text + " " + value + " " + str(fuzz.partial_ratio(text.lower(), value.lower())))
    words = text.split()
    for word in words:
        if is_float(word):
            listExtract.append({'key': 'DiemChuan', 'value': float(word)})
        if word in extractKhoiThi:
            listExtract.append({'key': 'KhoiThi', 'value': extractKhoiThi[word]})
    return listExtract


# In[13]:


extract('Em muốn học khối A00 thì thi trường nào vậy? Em thích trường đại học bách khoa')


# In[14]:


extract("Trường Đại học Thủ Dầu Một có ký túc xá không? học phí như thế nào?")


# In[15]:


extract('Em thi duoc 20 diem')


# In[16]:


extract('Khối C')


# In[ ]:




